<script lang="ts">
  import StatusLine from "$lib/components/ui/StatusLine.svelte";
  import { onMount } from "svelte";
  import AppButton from "$lib/components/ui/AppButton.svelte";
  import AppCard from "$lib/components/ui/AppCard.svelte";
  import { command } from "$lib/services/api";
  import { locale, t } from "$lib/i18n";
  let currentLocale = $derived($locale);
  const tt = (key: Parameters<typeof t>[0], params: Record<string, string | number> = {}) => t(key, params, currentLocale);
  type Schedule = { id:number; enabled:boolean; interval_minutes:number; daily_enabled:boolean; daily_hour:number; daily_minute:number; last_interval_run_at:number|null; last_daily_local_date:string|null; updated_at:number };
  let schedule = $state<Schedule | null>(null); let busy = $state(false); let message = $state(""); let error = $state(""); let runs = $state<Array<{id:number;trigger:string;status:string;started_at:number;finished_at:number|null;summary:string|null;error_code:string|null;error_message:string|null}>>([]);
  async function load(){try{schedule=await command<Schedule>("get_analysis_schedule");runs=await command("list_analysis_runs",{limit:5});error="";}catch(e){error=String(e);}}
  async function save(){if(!schedule)return;busy=true;try{schedule=await command<Schedule>("save_analysis_schedule",{schedule});message=tt("settings.scheduleSaved");}catch(e){error=String(e);}finally{busy=false;}}
  async function runNow(){busy=true;message="";error="";let failure="";try{const id=await command<number>("run_analysis_now",{trigger:"manual"});message=`${tt("settings.analysisStarted")} #${id}`;}catch(e){failure=String(e);}finally{await load();if(failure)error=failure;busy=false;}}
  let efficiency=$state<{reused_checks:number;input_chars_saved:number}|null>(null);
  onMount(()=>{void load();void command<{reused_checks:number;input_chars_saved:number}>('get_ai_efficiency_stats').then(value=>efficiency=value).catch(()=>{});});
</script>
<section class="schedule"><div class="section-head"><div><h2>{tt("settings.analysisSchedule")}</h2><p>{tt("settings.analysisScheduleHint")}</p></div><AppButton variant="secondary" onclick={runNow} loading={busy}>{tt("settings.runAnalysisNow")}</AppButton></div>
  <div class="error success stable-feedback"><StatusLine message={error||message} error={!!error}/></div>
  {#if schedule}<AppCard><div class="schedule-grid"><label class="toggle"><input type="checkbox" bind:checked={schedule.enabled} /><span>{tt("settings.analysisEnabled")}</span></label><label>{tt("settings.intervalMinutes")}<input type="number" min="30" max="1440" step="30" bind:value={schedule.interval_minutes} /></label><label class="toggle"><input type="checkbox" bind:checked={schedule.daily_enabled} /><span>{tt("settings.dailyAnalysis")}</span></label><label>{tt("settings.dailyTime")}<input type="time" value={`${String(schedule.daily_hour).padStart(2,"0")}:${String(schedule.daily_minute).padStart(2,"0")}`} onchange={(e)=>{const [h,m]=(e.currentTarget as HTMLInputElement).value.split(":").map(Number);schedule={...schedule!,daily_hour:h,daily_minute:m};}} /></label></div><div class="form-actions"><AppButton onclick={save} loading={busy}>{tt("common.save")}</AppButton></div><div class="muted">{tt("settings.defaultSchedule")}</div></AppCard>{/if}
  <AppCard><div class="efficiency" data-testid="ai-efficiency"><strong>{currentLocale==='en-US'?'Check regularly, request only when useful':'照常检查，有变化再分析'}</strong><p>{currentLocale==='en-US'?'A periodic check reuses analysis only with complete input coverage and unchanged facts, time milestones and model settings. Manual analysis always runs again.':'周期检查照常进行；输入覆盖完整，且事实、时间节点和模型配置均未变化时，复用成功分析。手动分析始终重新请求模型。'}</p>{#if efficiency}<span>{currentLocale==='en-US'?'Reused checks':'已复用检查'}：{efficiency.reused_checks} · {currentLocale==='en-US'?'Input characters removed':'累计减少输入字符'}：{efficiency.input_chars_saved.toLocaleString()}</span>{/if}<small>{currentLocale==='en-US'?'Character savings are not measured tokens or billing. Work details are retained.':'字符数仅表示输入压缩量，不等同于 token 或费用；事项细节仍然保留。'}</small></div></AppCard>
  <AppCard><strong>{tt("settings.recentAnalyses")}</strong>{#if !runs.length}<div class="muted">{tt("settings.noAnalyses")}</div>{:else}<div class="run-list">{#each runs as run}<div data-testid={`analysis-run-${run.id}`}><span><b>#{run.id} · {run.trigger}</b>{#if run.summary}<small>{run.summary}</small>{:else if run.error_message}<small class="run-error">{run.error_message}</small>{/if}</span><span class="tag">{run.status==='reused'?(currentLocale==='en-US'?'No changes':'无新变化'):run.status}</span></div>{/each}</div>{/if}</AppCard>
</section>
<style>.efficiency{display:grid;gap:9px;line-height:1.65}.efficiency p{margin:0}.efficiency small{font-size:13px;color:var(--color-muted)}.schedule{display:grid;gap:12px}.section-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.section-head h2{margin:0 0 4px;font-size:17px}.section-head p,.muted{color:var(--color-muted);font-size:12px}.schedule-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.schedule-grid label{display:grid;gap:6px;font-size:12px;color:var(--color-muted)}.schedule-grid input[type=number],.schedule-grid input[type=time]{border:1px solid var(--color-border);border-radius:8px;padding:8px;background:#fbfcfc;color:var(--color-text)}.toggle{display:flex!important;align-items:center;gap:8px}.form-actions{display:flex;justify-content:flex-end;margin-top:12px}.run-list{display:grid;gap:6px;margin-top:9px}.run-list>div{display:flex;justify-content:space-between;gap:12px;border-top:1px solid var(--color-border);padding-top:7px;font-size:11px}.run-list>div>span:first-child{min-width:0;display:grid;gap:3px}.run-list small{color:var(--color-muted);white-space:normal}.run-list .run-error{color:var(--color-danger)}.tag{height:max-content;border:1px solid var(--color-border);border-radius:999px;padding:2px 7px}.error{color:var(--color-danger)}.success{color:var(--color-success)}@media(max-width:700px){.schedule-grid{grid-template-columns:1fr}.section-head{flex-direction:column}}</style>
