<script lang="ts">
 import {onMount,onDestroy} from 'svelte';
 import {open as choose} from '@tauri-apps/plugin-dialog';
 import {command,normalizeError} from '$lib/services/api';
 import {locale} from '$lib/i18n';
 import AppButton from './ui/AppButton.svelte';import StatusLine from './ui/StatusLine.svelte';import Modal from './ui/Modal.svelte';
 type Config={directory:string;enabled:boolean;interval_minutes:number;keep_count:number};
 type Info={data_directory:string;cache_directory:string;config:Config;state:{last_success:number;last_file:string;error:string;warning:string;files:string[]};running:boolean;restore_pending:boolean;has_rollback:boolean};
 type Preview={token:string;manifest:{created_at:number;app_version:string;files:{name:string;bytes:number}[]}};
 let status=$state<Info|null>(null), directory=$state(''),enabled=$state(false),minutes=$state(1440),keep=$state(7),busy=$state(false),message=$state(''),error=$state(''),file=$state(''),preview=$state<Preview|null>(null),modal=$state(false),confirmation=$state(''),composing=$state(false);
 let initialized=false,alive=true;let en=$derived($locale==='en-US');const L=(zh:string,enText:string)=>en?enText:zh;
 const time=(n:number)=>n?new Date(n*1000).toLocaleString(en?'en-US':'zh-CN'):L('尚无备份','No backup yet');
 async function load(){try{status=await command<Info>('backup_status');if(!initialized){({directory,enabled}=status.config);minutes=status.config.interval_minutes;keep=status.config.keep_count;initialized=true;}}catch(e){error=normalizeError(e);}}
 async function selectDirectory(){const p=await choose({directory:true,multiple:false});if(typeof p==='string')directory=p;}
 async function preparePrivate(){busy=true;error='';try{directory=await command<string>('prepare_private_cloud_folder',{directory});message=L('私有子文件夹已创建并排除 Git。请保存备份设置；不要强制添加此目录到 Git。','Private folder created and excluded from Git. Save backup settings; do not force-add it to Git.');}catch(e){error=normalizeError(e);}finally{busy=false;}}
 async function save(){busy=true;error='';try{await command('save_backup_settings',{directory,enabled,intervalMinutes:Number(minutes),keepCount:Number(keep)});message=L('备份设置已保存','Backup settings saved');await load();}catch(e){error=normalizeError(e);}finally{busy=false;}}
 async function backup(){busy=true;error='';try{await command('create_backup');message=L('备份已保存并校验；云端同步请查看云盘客户端。','Backup saved and verified. Check your cloud client for upload status.');await load();}catch(e){error=normalizeError(e);}finally{busy=false;}}
 async function selectFile(){const p=await choose({multiple:false,filters:[{name:'MSL Backup',extensions:['mslbackup']}]});if(typeof p==='string')file=p;}
 function discard(){const token=preview?.token;preview=null;if(token)void command('discard_backup_preview',{token}).catch(()=>{});}
 async function inspect(){busy=true;error='';try{const result=await command<Preview>('preview_backup_restore',{path:file});if(!alive){void command('discard_backup_preview',{token:result.token}).catch(()=>{});return;}preview=result;confirmation='';composing=false;modal=true;}catch(e){error=normalizeError(e);}finally{busy=false;}}
 async function restore(){if(!preview||confirmation.trim()!=='恢复备份'||composing)return;busy=true;error='';try{await command('confirm_backup_restore',{token:preview.token,confirmationName:confirmation});await command('restart_after_restore');}catch(e){error=normalizeError(e);await load();}finally{busy=false;}}
 onMount(()=>{void load();const timer=setInterval(()=>void load(),3000);return()=>clearInterval(timer);});
 onDestroy(()=>{alive=false;discard();});
 $effect(()=>{if(!modal&&!busy&&preview)discard();});
</script>
<section class="backup-settings" data-testid="backup-settings">
 <details class="history" data-testid="backup-history">
 <summary class="history-summary"><span><strong>{L('历史备份与恢复','Backup & recovery')}</strong><span class="summary-hint">{L('保留历史副本，便于误删后找回。同步中的删除可能传播到其他设备。','Keep snapshots for recovery. Deletions may propagate through sync.')}</span></span><span class="backup-state">{status?.running?L('正在备份…','Backing up…'):time(status?.state.last_success??0)}</span></summary>
 <div class="history-body">
 <div class="actions"><AppButton testid="backup-now" loading={busy||status?.running} disabled={!status?.config.directory||status?.restore_pending} onclick={backup}>{L('立即备份','Back up now')}</AppButton><span class="note">{status?.config.directory?L('保存到已配置的备份文件夹','Saves to your configured backup folder'):L('首次使用，请展开下方设置选择备份位置','Choose a backup location in the settings below to begin')}</span></div>
 <details class="advanced" data-testid="backup-advanced"><summary>{L('备份设置 · 位置、周期与保留份数','Backup settings · location, schedule & retention')}</summary><div class="advanced-body">
 <div class="folder-row"><label>{L('备份文件夹','Backup folder')}<input data-testid="backup-directory" bind:value={directory} placeholder={L('选择独立文件夹，可粘贴路径','Choose a separate folder or paste its path')}/></label><AppButton variant="secondary" disabled={busy} onclick={selectDirectory}>{L('选择文件夹','Choose folder')}</AppButton></div>
 {#if error.includes('GIT_PRIVATE_FOLDER_REQUIRED')}<div class="actions"><AppButton variant="secondary" loading={busy} onclick={preparePrivate}>{L('创建私有云盘子文件夹','Create private cloud subfolder')}</AppButton><span class="note">{L('将在所选位置创建 MSLDesktop-private 和 Git 排除文件，现有文件保持原样。','Creates MSLDesktop-private with a Git exclusion file; existing files stay unchanged.')}</span></div>{/if}
 <div class="policy-row"><label class="toggle"><input type="checkbox" bind:checked={enabled}/>{L('自动备份','Automatic backup')}</label><label>{L('间隔（分钟）','Interval (minutes)')}<input data-testid="backup-interval" type="number" min="30" max="10080" bind:value={minutes}/></label><label>{L('保留份数','Copies to keep')}<input data-testid="backup-retention" type="number" min="1" max="100" bind:value={keep}/></label></div>
 <p class="note">{L('自动备份在应用或托盘运行期间执行。仅清理本机创建且校验通过的旧备份；其他文件保持原样。','Automatic backups run while the app or tray is active. Retention only removes verified backups created by this installation.')}</p>
 <div class="actions"><AppButton variant="secondary" testid="backup-save" loading={busy} onclick={save}>{L('保存备份设置','Save backup settings')}</AppButton></div>
 </div></details>
 <div class="last-backup"><strong>{status?.running?L('正在后台备份，可切换页面','Backing up in the background'):L('最近成功备份','Last successful backup')}</strong><span>{time(status?.state.last_success??0)}</span>{#if status?.state.last_file}<code>{status.state.last_file}</code>{/if}</div>
 <details><summary>{L('备份包含什么？','What is included?')}</summary><p>{L('项目、任务、等待事项、日历、收件箱、简报与报告、问答、专家与资料、分类记忆和应用设置。原始工作目录仅保留关联记录；源文件、缓存、临时文件和 Windows 凭据不打包。','Includes projects, tasks, waiting items, calendars, inbox, briefs, reports, conversations, experts and materials, memories and app preferences. External work folders are linked only. Source files, caches and Windows credentials are excluded.')}</p><p>{L('备份包未加密，请存放在私有文件夹。更换电脑后需要重新填写 API Key，并核对工作目录路径。','Archives are not encrypted: store them privately. On another computer, re-enter API keys and check workspace paths.')}</p></details>
 <div class="restore-section"><h3>{L('从备份恢复','Restore a backup')}</h3><p>{L('先检查备份，再确认并重新启动。恢复会替换工作台记录，原始工作文件保持原样。','Validate the archive, then confirm and restart. Restore replaces workbench records and leaves original work files untouched.')}</p><div class="folder-row"><label class="grow">{L('备份文件','Backup file')}<input data-testid="backup-file" bind:value={file} placeholder=".mslbackup"/></label><AppButton variant="secondary" disabled={busy} onclick={selectFile}>{L('选择文件','Choose file')}</AppButton></div><AppButton testid="backup-inspect" variant="secondary" loading={busy} disabled={!file||status?.running||status?.restore_pending} onclick={inspect}>{L('检查并预览恢复','Validate & preview')}</AppButton>
 {#if status?.restore_pending}<p class="warning">{L('恢复已确认，下一次启动将替换当前工作台数据。请先完成重启。','Restore is confirmed and will replace current data at the next startup. Restart before continuing.')}</p><AppButton onclick={()=>command('restart_after_restore')}>{L('重新启动并恢复','Restart and restore')}</AppButton>{/if}
 {#if status?.has_rollback}<p>{L('上一次恢复前的数据已保存在正式数据目录的 .restore-…/previous 中，可供故障回滚。','The previous data is retained under .restore-…/previous in your data folder for recovery.')}</p>{/if}</div>
 </div></details>
 <div class="backup-feedback"><StatusLine message={error||message||status?.state.error||status?.state.warning||(status?.restore_pending?L('已安排恢复，请展开“历史备份与恢复”完成重启','Restore pending. Open Backup & recovery to restart.'):'')} error={!!(error||status?.state.error)}/></div>
 <details class="local-storage"><summary>{L('本机存储位置 · 数据与应用独立保存','Local storage · separate from the application')}</summary><div class="locations"><div><span>{L('正式数据','Personal data')}</span><code>{status?.data_directory||'—'}</code></div><div><span>{L('缓存与临时文件','Cache & temporary files')}</span><code>{status?.cache_directory||'—'}</code></div></div></details>
</section>
<Modal bind:open={modal} title={L('确认恢复工作台数据','Confirm data restore')} dismissible={!busy}>
 {#if preview}<p>{L('备份时间：','Backup created: ')}{time(preview.manifest.created_at)}</p><p>MSL Desktop {preview.manifest.app_version} · {preview.manifest.files.length} {L('个数据文件','data files')}</p>{/if}
 <ul><li>{L('当前工作台记录将被替换，恢复前的副本会保留。','Current records will be replaced; the previous data will be retained.')}</li><li>{L('源工作文件与本机 API Key 保持原样。','Original work files and this device’s API keys remain unchanged.')}</li><li>{L('恢复后自动分析和备份暂停；请重新确认工作目录。','Automatic analysis and backup pause after restore. Review workspace bindings.')}</li></ul>
 <label class="confirm-label">{L('请输入“恢复备份”确认，然后重新启动：','Type 恢复备份 to confirm and restart:')}<input data-testid="restore-name" bind:value={confirmation} oncompositionstart={()=>composing=true} oncompositionend={()=>composing=false} disabled={busy}/></label>
 <StatusLine message={error} error={!!error}/>
 {#snippet footer()}<AppButton variant="secondary" disabled={busy} onclick={()=>modal=false}>{L('取消','Cancel')}</AppButton><AppButton testid="restore-confirm" variant="danger" loading={busy} disabled={confirmation.trim()!=='恢复备份'||composing} onclick={restore}>{L('确认并重启恢复','Confirm & restart')}</AppButton>{/snippet}
</Modal>
<style>
 .backup-settings{display:grid;gap:8px;min-width:0;align-content:start}.backup-settings h3{margin:0}.backup-settings p{margin:6px 0;line-height:1.75;color:var(--color-muted)}.locations{display:grid;gap:10px;padding:14px;background:var(--color-surface-muted);border-radius:10px}.locations>div{display:grid;grid-template-columns:140px minmax(0,1fr);gap:12px}.locations span,.note{color:var(--color-muted)}code{white-space:normal;overflow-wrap:anywhere;font:inherit;font-size:13px}.folder-row{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:end;gap:12px}label{display:grid;gap:8px;min-width:0}input:not([type=checkbox]){width:100%;min-width:0;padding:8px 12px}.policy-row{display:grid;grid-template-columns:minmax(140px,1fr) 180px 140px;gap:18px;align-items:end}.toggle{display:flex;align-items:center;gap:8px;min-height:40px}.actions{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.last-backup{display:grid;gap:8px;padding:14px 0;border-top:1px solid var(--color-border)}.last-backup span{color:var(--color-muted)}details{border-top:1px solid var(--color-border);padding-top:14px}summary{cursor:pointer;line-height:1.6;overflow-wrap:anywhere}.restore-section{display:grid;gap:12px;border-top:1px solid var(--color-border);padding-top:20px}.restore-section>:global(button){justify-self:start}.confirm-label{display:grid;gap:10px;margin:20px 0}ul{line-height:1.9;padding-left:20px}.warning{color:var(--color-warning)!important}
 .history{border:1px solid var(--color-border);border-radius:12px;padding:0;min-width:0}.history-summary{display:flex;align-items:center;gap:12px;padding:16px;list-style:none}.history-summary::-webkit-details-marker{display:none}.history-summary::before{content:'›';font-size:22px;color:var(--color-muted);flex:none;transition:transform .15s}.history[open]>.history-summary::before{transform:rotate(90deg)}.history-summary>span:first-of-type{flex:1;min-width:0}.summary-hint{display:block;color:var(--color-muted);font-size:13px;margin-top:4px}.backup-state{color:var(--color-muted);font-size:13px;max-width:35%;overflow-wrap:anywhere}.history-body,.advanced-body{display:grid;gap:16px;padding:16px;min-width:0;align-content:start}.history-body{border-top:1px solid var(--color-border)}.advanced-body{padding-inline:0}.local-storage{padding-top:0;border:0;color:var(--color-muted)}.local-storage .locations{margin-top:10px}.backup-feedback{min-width:0}
 @container(max-width:650px){.policy-row{grid-template-columns:1fr 1fr}.toggle{grid-column:1/-1}.locations>div{grid-template-columns:1fr;gap:4px}.folder-row{grid-template-columns:minmax(0,1fr)}.folder-row>:global(button){justify-self:start}.history-summary{flex-wrap:wrap}.backup-state{max-width:100%;margin-left:24px}}
</style>
