<script lang="ts">
 import '$lib/styles/knowledge.css';
 import {onMount} from 'svelte';
 import {locale} from '$lib/i18n';
 import {command,normalizeError,listWorks} from '$lib/services/api';
 import {navigateTo} from '$lib/services/navigation';
 import {aiJobs} from '$lib/stores/aiJobs';
 import {json,categories,localTime,parseLocalTime,type Expert,type Project,type KolDraft,type Citation,type Pack} from '$lib/services/knowledge';
 import KolDraftEditor from './KolDraftEditor.svelte';
 import KnowledgeSources from './KnowledgeSources.svelte';
 type Note={id:number;content:string;occurred_at:number;name:string;institution:string;department:string;project_title:string|null};
 type InsightRecord={id:number;name:string|null;title:string;categories_json:string;observation:string;implication:string;uncertainty:string;next_question:string;citations_json:string;status:string;review_note:string;draft_id:number};
 type Followup={id:number;name:string;entity_kind:string;entity_id:number;title:string;status:string;work_id:number|null;at:number|null};
 let {focusId=null}:{focusId?:number|null}=$props();
 let en=$derived($locale==='en-US');
 let experts=$state<Expert[]>([]),projects=$state<Project[]>([]),notes=$state<Note[]>([]),drafts=$state<KolDraft[]>([]),insights=$state<InsightRecord[]>([]),followups=$state<Followup[]>([]),inbox=$state<{id:number;content:string}[]>([]);
 let expertId=$state<number|null>(null),draftId=$state<number|null>(null),tab=$state('record'),search=$state(''),category=$state(''),error=$state(''),notice=$state(''),busy=$state(false);
 let editing=$state(false),editId=$state<number|null>(null),editRevision=$state<number|null>(null),name=$state(''),institution=$state(''),department=$state(''),specialty=$state(''),editProjects=$state<number[]>([]),archived=$state(false);
 let content=$state(''),at=$state(localTime(Math.floor(Date.now()/1000))),workId=$state<number|null>(null),inboxId=$state<number|null>(null);
 let expert=$derived(experts.find(e=>e.id===expertId)),draft=$derived(drafts.find(d=>d.id===draftId));
 let running=$derived($aiJobs.some(j=>j.command==='analyze_kol'&&j.status==='running'));
 let filtered=$derived(experts.filter(e=>`${e.name} ${e.institution} ${e.department} ${e.specialty}`.toLowerCase().includes(search.toLowerCase())));
 async function load(){const id=expertId;const results=await Promise.all([command<Expert[]>('list_kol_experts'),command<Note[]>('list_kol_notes',{expertId:id}),command<KolDraft[]>('list_kol_drafts',{expertId:id}),command<InsightRecord[]>('list_kol_insights',{expertId:id}),command<Followup[]>('list_kol_followups',{expertId:id})]);if(id!==expertId)return;[experts,notes,drafts,insights,followups]=results;if(!drafts.some(d=>d.id===draftId))draftId=drafts[0]?.id??null;}
 async function choose(id:number|null){expertId=id;draftId=null;tab='record';content='';inboxId=null;workId=null;notice='';try{await load();}catch(e){error=normalizeError(e);}}
 function edit(e?:Expert){editing=true;editId=e?.id??null;editRevision=e?.revision??null;name=e?.name??'';institution=e?.institution??'';department=e?.department??'';specialty=e?.specialty??'';editProjects=json(e?.project_ids_json,[]);archived=Boolean(e?.archived);}
 async function saveExpert(){busy=true;error='';try{const saved=await command<Expert>('save_kol_expert',{id:editId,revision:editRevision,name,institution,department,specialty,projects:editProjects,archived});editing=false;await choose(saved.id);}catch(e){error=normalizeError(e);}finally{busy=false;}}
 async function analyze(purpose:string){busy=true;error='';notice=en?'Analysis continues in the background.':'分析已在后台进行，可以切换页面。';try{const result=await command<{draft_id:number;expert_id:number|null}>('analyze_kol',{expertId:purpose==='synthesize'?null:expertId,purpose,locale:$locale});if(purpose==='synthesize')expertId=null;await load();draftId=result.draft_id;tab='drafts';notice=en?'Draft ready. Review it before creating follow-ups.':'草稿已生成，确认后才会写入跟进事项。';}catch(e){error=normalizeError(e);}finally{busy=false;}}
 async function capture(organize:boolean){busy=true;error='';try{await command('capture_kol_note',{expertId,workId,inboxId,content,occurredAt:parseLocalTime(at)});content='';inboxId=null;notice=en?'Original note saved.':'交流原话已保存。';await load();if(organize)await analyze('organize');}catch(e){error=normalizeError(e);}finally{busy=false;}}
 async function reviewInsight(i:InsightRecord){try{await command('review_kol_insight',{id:i.id,status:i.status,note:i.review_note});notice=en?'Insight review saved.':'洞察审阅已保存。';}catch(e){error=normalizeError(e);}}
 onMount(()=>{let active=true;void (async()=>{try{[projects,inbox]=await Promise.all([listWorks(),command<{id:number;content:string}[]>('list_inbox')]);if(active){expertId=focusId;await load();}}catch(e){error=normalizeError(e);}})();const timer=setInterval(()=>{void command<KolDraft[]>('list_kol_drafts',{expertId}).then(next=>{drafts=next;if(!draftId)draftId=next[0]?.id??null;}).catch(()=>{});},2400);return()=>{active=false;clearInterval(timer);};});
</script>
<section class="knowledge-page" data-testid="kol-page">
 <header class="k-head"><div><h1>{en?'Experts & insights':'专家与洞察'}</h1><p class="muted">{en?'Capture what you heard. Notice what matters. Follow through.':'记下交流中值得留意的内容，让洞察自然进入下一步工作。'}</p></div><div class="k-actions"><button data-testid="kol-new" onclick={()=>edit()}>＋ {en?'Add expert':'添加专家'}</button><button data-testid="kol-synthesize" disabled={busy||running||!experts.length} onclick={()=>analyze('synthesize')}>{en?'Find patterns across experts':'跨专家寻找共性'}</button></div></header>
 {#if error}<div class="k-error" role="alert">{error}<button onclick={()=>error=''} aria-label={en?'Dismiss':'关闭'}>×</button></div>{/if}
 {#if notice||running}<p class="k-pill" role="status">{running?(en?'AI analysis is running in the background.':'AI 正在后台整理，结果会保存在“整理草稿”。'):notice}</p>{/if}
 {#if editing}<section class="k-card k-stack" data-testid="kol-profile-editor"><h2>{editId?(en?'Edit expert':'编辑专家资料'):(en?'Start with a name and institution':'从姓名和机构开始')}</h2><div class="k-fields"><label>{en?'Name':'姓名'}<input data-testid="kol-name" bind:value={name} maxlength="100"/></label><label>{en?'Institution':'机构'}<input data-testid="kol-institution" bind:value={institution} maxlength="200"/></label><label>{en?'Department (optional)':'科室（可稍后补充）'}<input data-testid="kol-department" bind:value={department} maxlength="200"/></label><label>{en?'Focus areas (optional)':'关注领域（可稍后补充）'}<input bind:value={specialty} maxlength="400"/></label></div><details><summary>{en?'Related projects':'关联项目'} · {editProjects.length}</summary><div class="k-actions">{#each projects as p(p.id)}<label class="k-check"><input type="checkbox" checked={editProjects.includes(p.id)} onchange={e=>editProjects=e.currentTarget.checked?[...editProjects,p.id]:editProjects.filter(id=>id!==p.id)}/>{p.title}</label>{/each}</div></details>{#if editId}<label class="k-check"><input type="checkbox" bind:checked={archived}/>{en?'Archive this profile (keep history)':'归档此专家（保留历史）'}</label>{/if}<div class="k-actions"><button class="primary" data-testid="kol-save-expert" disabled={busy||!name.trim()||!institution.trim()} onclick={saveExpert}>{en?'Save expert':'保存专家'}</button><button onclick={()=>editing=false}>{en?'Cancel':'取消'}</button></div></section>{/if}
 <div class="k-grid"><aside class="k-card k-stack"><label>{en?'Find an expert':'找一位专家'}<input data-testid="kol-search" bind:value={search} placeholder={en?'Name, institution, department or focus':'姓名、机构、科室或关注领域'}/></label><button class:selected={expertId===null} onclick={()=>choose(null)}>{en?'All experts & shared insights':'全部专家 · 共性洞察'}</button><div class="k-list">{#each filtered as e(e.id)}<button data-testid={`kol-expert-${e.id}`} class:selected={expertId===e.id} onclick={()=>choose(e.id)}><strong>{e.name}{e.archived?' · '+(en?'Archived':'已归档'):''}</strong><span class="muted">{e.institution}</span>{#if e.department}<small class="muted">{e.department}</small>{/if}<small class="muted">{e.note_count} {en?'interactions':'次交流'}{e.last_contact?' · '+new Date(e.last_contact*1000).toLocaleDateString($locale):''}</small></button>{:else}<p class="muted">{en?'Add an expert after a useful conversation.':'从一次有价值的交流开始添加专家。'}</p>{/each}</div></aside>
 <main class="k-stack">
  <section class="k-card k-stack"><div class="k-head"><div><h2>{expert?.name??(en?'Look across conversations':'从交流中发现线索')}</h2><p class="muted">{expert?[expert.institution,expert.department,expert.specialty].filter(Boolean).join(' · '):(en?'Practice barriers · Evidence needs · Research opportunities':'临床实践障碍 · 证据需求 · 研究合作机会')}</p></div>{#if expert}<div class="k-actions"><button onclick={()=>navigateTo({view:'qa',workId:json<number[]>(expert?.project_ids_json,[])[0]})}>{en?'Ask the workbench':'向工作台提问'}</button><button data-testid="kol-edit-profile" onclick={()=>edit(expert)}>{en?'Profile':'资料'}</button><button disabled={busy||running||!notes.length} onclick={()=>analyze('prepare')}>{en?'Prepare next conversation':'准备下次交流'}</button></div>{/if}</div>
   {#if expert?.summary}<p class="summary">{expert.summary}</p>{/if}
   <nav class="k-actions" aria-label={en?'Expert sections':'专家内容'}>{#each [['record','记交流','Record'],['drafts','整理草稿','Drafts'],['insights','洞察','Insights'],['followups','跟进','Follow-ups']] as section}<button data-testid={`kol-tab-${section[0]}`} class:selected={tab===section[0]} onclick={()=>tab=section[0]}>{section[en?2:1]}{section[0]==='drafts'?` · ${drafts.filter(d=>d.status==='pending').length}`:''}</button>{/each}</nav>
  </section>
  {#if tab==='record'}
   {#if expert&&!expert.archived}<section class="k-card k-stack"><h2>{en?'What stood out in the conversation?':'这次交流，有什么值得留意？'}</h2><p class="muted">{en?'A few natural sentences are enough. Keep names anonymous for any patient information.':'用几句自然的话记下来即可。如涉及患者信息，请先去除身份细节。'}</p>
   <details><summary>{en?'Use an existing inbox note':'从收件箱带入已有记录'}</summary><select aria-label={en?'Inbox note':'选择收件箱记录'} bind:value={inboxId} onchange={()=>content=inbox.find(i=>i.id===inboxId)?.content??''}><option value={null}>{en?'Write a new note':'填写新交流'}</option>{#each inbox as i(i.id)}<option value={i.id}>{i.content.slice(0,80)}</option>{/each}</select><p class="muted">{en?'Original inbox text is preserved and linked.':'保存时关联收件箱原文，收件箱原记录保留。'}</p></details>
   <textarea data-testid="kol-note" bind:value={content} disabled={inboxId!==null} rows="5" maxlength="20000" placeholder={en?'What did the expert ask, observe or need? Any promise to follow up?':'专家提到了什么、有什么疑问？有什么需要后续兑现的承诺？'}></textarea><div class="k-fields"><label>{en?'When':'交流时间'}<input type="datetime-local" bind:value={at}/></label><label>{en?'Project (optional)':'归属项目（可暂不选）'}<select bind:value={workId}><option value={null}>{en?'Independent / to clarify':'临时事务 / 待明确'}</option>{#each projects as p(p.id)}<option value={p.id}>{p.title}</option>{/each}</select></label></div><div class="k-actions"><button class="primary" data-testid="kol-save-analyze" disabled={busy||running||!content.trim()||!at} onclick={()=>capture(true)}>{en?'Save & let AI organize':'保存并让 AI 整理'}</button><button data-testid="kol-save-note" disabled={busy||!content.trim()||!at} onclick={()=>capture(false)}>{en?'Just save for now':'先记下来'}</button>{#if notes.length}<button disabled={busy||running} onclick={()=>analyze('organize')}>{en?'Organize saved interactions':'整理已有交流'}</button>{/if}</div></section>
   {:else if !expert}<div class="k-card k-empty"><h2>{en?'Pick an expert, then record naturally':'选择专家，随手记下交流'}</h2><p>{en?'Shared insights appear in Drafts after across-expert analysis.':'跨专家分析完成后，可在“整理草稿”查看共性洞察。'}</p></div>{/if}
   <section class="k-card k-stack"><h2>{en?'Original interactions':'交流原话'}</h2>{#each notes as note(note.id)}<article class="k-rule"><strong>{[note.name,note.institution,note.department].filter(Boolean).join(' · ')}</strong><p class="muted">{new Date(note.occurred_at*1000).toLocaleString($locale)}{note.project_title?' · '+note.project_title:''}</p><p class="original">{note.content}</p></article>{:else}<p class="muted">{en?'No interactions recorded yet.':'还没有交流记录。'}</p>{/each}</section>
  {:else if tab==='drafts'}
   <div class="k-actions">{#each drafts as d(d.id)}<button class:selected={d.id===draftId} onclick={()=>draftId=d.id}>#{d.id} · {d.name??(en?'All experts':'跨专家')} · {d.status==='pending'?(en?'To review':'待确认'):d.status==='confirmed'?(en?'Confirmed':'已确认'):(en?'Rejected':'已拒绝')}</button>{/each}</div>
   {#if draft}{#key `${draft.id}-${draft.revision}`}<KolDraftEditor {draft} {projects} onchange={()=>void load()}/>{/key}{:else}<div class="k-card k-empty">{en?'Save an interaction and ask AI to organize it.':'记下一次交流，再让 AI 帮您整理。'}</div>{/if}
  {:else if tab==='insights'}
   <div class="k-actions"><button class:selected={!category} onclick={()=>category=''}>{en?'All categories':'全部类型'}</button>{#each categories as c}<button class:selected={category===c[0]} onclick={()=>category=c[0]}>{c[en?2:1]}</button>{/each}</div>
   {#each insights.filter(i=>!category||json<string[]>(i.categories_json,[]).includes(category)) as insight(insight.id)}
   <article class="k-card k-stack"><div><p class="muted">{insight.name??(en?'Across experts':'跨专家共性')}</p><h2>{insight.title}</h2></div><div class="k-actions">{#each json<string[]>(insight.categories_json,[]) as c}<span class="k-pill">{categories.find(x=>x[0]===c)?.[en?2:1]??c}</span>{/each}</div>
   <div><h3>{en?'Observation':'观察 / 表达'}</h3><p>{insight.observation}</p></div><div><h3>{en?'Possible significance':'可能的意义'}</h3><p>{insight.implication||'—'}</p></div><div><h3>{en?'Uncertainty and next question':'不确定性与下一次追问'}</h3><p>{insight.uncertainty}</p><p>{insight.next_question}</p></div>
   <KnowledgeSources citations={json<Citation[]>(insight.citations_json,[])} pack={json<Pack|null>(drafts.find(d=>d.id===insight.draft_id)?.evidence_json,null)}/>
   <details><summary>{en?'Update your assessment':'更新您的判断'}</summary><div class="k-stack"><label>{en?'Current assessment':'当前判断'}<select bind:value={insight.status}><option value="hypothesis">{en?'Hypothesis to verify':'待验证假设'}</option><option value="reviewed">{en?'Reviewed by me':'我已核对'}</option><option value="revised">{en?'Revised interpretation':'需要修正理解'}</option><option value="dismissed">{en?'Not supported':'暂不支持'}</option></select></label><label>{en?'Correction or new evidence':'修正理解 / 新依据'}<textarea bind:value={insight.review_note}></textarea></label><button onclick={()=>reviewInsight(insight)}>{en?'Save assessment':'保存判断'}</button></div></details>
   </article>{:else}<div class="k-card k-empty">{en?'Confirmed insights will appear here. Expert views are not established medical conclusions.':'确认后的洞察会出现在这里。专家观点需与已证实的医学结论区分。'}</div>{/each}
  {:else if tab==='followups'}<section class="k-card k-stack"><h2>{en?'Keep the conversation moving':'让交流继续推进'}</h2><p class="muted">{en?'These are the same tasks, waiting items and calendar records used elsewhere in the workbench.':'这里与任务计划、等待事项和日历共用同一条记录，状态会同步变化。'}</p>{#each followups as item(item.id)}<div class="k-head k-rule"><div><strong>{item.title}</strong><p class="muted">{item.name} · {item.work_id?projects.find(p=>p.id===item.work_id)?.title:(en?'Independent':'临时事务')}{item.at?' · '+new Date(item.at*1000).toLocaleString($locale):''}</p></div><button onclick={()=>navigateTo(item.entity_kind,item.entity_id)}>{en?'Continue':'继续处理'} ↗</button></div>{:else}<p class="k-empty">{en?'No open follow-ups. Choose useful actions when reviewing a draft.':'暂无未完成跟进，可在审阅草稿时选择有价值的后续动作。'}</p>{/each}</section>{/if}
 </main></div>
</section>
<style>.original,.summary{white-space:pre-wrap;overflow-wrap:anywhere}.original{font-size:16px}summary{cursor:pointer;padding:8px 0}.k-error{display:flex;align-items:center;justify-content:space-between;gap:10px}.k-rule strong{font-size:16px}</style>
