<script lang="ts">
  import { onMount } from "svelte";
  import AppButton from "$lib/components/ui/AppButton.svelte";
  import AppCard from "$lib/components/ui/AppCard.svelte";
  import { command } from "$lib/services/api";
  import { locale, t } from "$lib/i18n";
  let currentLocale=$derived($locale);const tt=(key:Parameters<typeof t>[0],p:Record<string,string|number>={})=>t(key,p,currentLocale);
  type Usage={categories:Array<{category:string;bytes:number;count:number;protected:number}>;cache_bytes:number;database_bytes:number;cache_limit_bytes:number;high_water_percent:number;target_percent:number;last_cleanup_at:number|null};type Plan={plan_id:string;estimated_bytes:number;estimated_count:number;protected_counts:Record<string,number>;warnings:string[]};
  let usage=$state<Usage|null>(null);let plan=$state<Plan|null>(null);let busy=$state(false);let error=$state("");let message=$state("");let advanced=$state(false);
  const fmt=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
  async function load(){try{usage=await command<Usage>("get_storage_usage");error="";}catch(e){error=String(e);}}
  async function preview(){busy=true;try{plan=await command<Plan>("preview_storage_cleanup",{categories:null});}catch(e){error=String(e);}finally{busy=false;}}
  async function execute(){if(!plan)return;busy=true;try{const result=await command<{deleted_count:number;skipped_count:number;failed_count:number}>("execute_storage_cleanup",{planId:plan.plan_id});message=tt("storage.cleanupDone",{deleted:result.deleted_count,skipped:result.skipped_count,failed:result.failed_count});plan=null;await load();}catch(e){error=String(e);}finally{busy=false;}}
  async function compact(){busy=true;try{await command("compact_storage_history");message=tt("storage.compactDone");}catch(e){error=String(e);}finally{busy=false;}}
  async function clearWebview(){if(!confirm(tt("storage.confirmWebview")))return;busy=true;try{await command("clear_webview_data");message=tt("storage.webviewDone");}catch(e){error=String(e);}finally{busy=false;}}
  onMount(load);
</script>
<section class="storage-settings"><div class="section-head"><div><h2>{tt("storage.title")}</h2><p>{tt("storage.hint")}</p></div><AppButton variant="secondary" onclick={load}>{tt("common.refresh")}</AppButton></div>{#if error}<div class="error" role="alert">{error}</div>{/if}{#if message}<div class="success">{message}</div>{/if}{#if usage}<AppCard><div class="usage-head"><strong>{tt("storage.cacheTotal")}</strong><strong>{fmt(usage.cache_bytes)}</strong></div><div class="usage-bar"><span style={`width:${Math.min(100,usage.cache_bytes/usage.cache_limit_bytes*100)}%`}></span></div><div class="muted">{tt("storage.policy",{limit:fmt(usage.cache_limit_bytes),high:usage.high_water_percent,target:usage.target_percent})}</div><div class="usage-grid"><div><span>{tt("storage.database")}</span><strong>{fmt(usage.database_bytes)}</strong></div>{#each usage.categories as item}<div><span>{item.category}</span><strong>{fmt(item.bytes)}</strong><small>{item.count} {tt("storage.items")}</small></div>{/each}</div></AppCard>{/if}<AppCard><div class="actions"><AppButton onclick={preview} loading={busy}>{tt("storage.smartCleanup")}</AppButton><AppButton variant="secondary" onclick={compact} loading={busy}>{tt("storage.compact")}</AppButton><AppButton variant="ghost" onclick={()=>advanced=!advanced}>{tt("storage.advanced")}</AppButton></div>{#if advanced}<div class="advanced"><p class="muted">{tt("storage.protected")}</p><AppButton variant="ghost" onclick={clearWebview} loading={busy}>{tt("storage.clearWebview")}</AppButton></div>{/if}{#if plan}<div class="plan"><strong>{tt("storage.previewTitle")}</strong><p>{tt("storage.previewSummary",{count:plan.estimated_count,bytes:fmt(plan.estimated_bytes)})}</p><p class="muted">{plan.warnings.join(" ")}</p><div class="actions"><AppButton variant="ghost" onclick={()=>plan=null}>{tt("common.cancel")}</AppButton><AppButton variant="danger" onclick={execute} loading={busy}>{tt("storage.confirmCleanup")}</AppButton></div></div>{/if}</AppCard></section>
<style>.storage-settings{display:grid;gap:12px}.section-head,.usage-head,.actions{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.section-head h2{margin:0 0 4px;font-size:17px}.section-head p,.muted{margin:0;color:var(--color-muted);font-size:12px}.usage-bar{height:7px;background:var(--color-surface-muted);border-radius:9px;overflow:hidden;margin:9px 0}.usage-bar span{display:block;height:100%;background:linear-gradient(90deg,#8199a4,#6f898f)}.usage-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin-top:12px}.usage-grid>div{border:1px solid var(--color-border);border-radius:9px;padding:8px;display:grid;gap:3px;background:#fafcfc}.usage-grid span,.usage-grid small{font-size:10px;color:var(--color-muted)}.usage-grid strong{font-size:14px}.actions{justify-content:flex-start;flex-wrap:wrap}.advanced,.plan{border-top:1px solid var(--color-border);padding-top:11px;margin-top:11px;display:grid;gap:7px}.error{color:var(--color-danger)}.success{color:var(--color-success)}@media(max-width:700px){.usage-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.section-head{flex-direction:column}}</style>
